import Button from "@/components/Button";
import Wrapper from "@/components/Wrapper";
import IconCancel from "@/svg/IconCancel";
import Head from "next/head";
import { useEffect, useState } from "react";

export default function Edit() {
  const [s, setS] = useState<number | string>("");
  const [t, setT] = useState<string>("");
  useEffect(() => {
    if (Number(s) > 99) {
      setS(99);
    }
    if (Number(s) < 0) {
      setS("");
    }
  }, [s]);

  return (
    <>
      <Head>
        <title>Sales Drive - OLX | Edit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <div className="flex gap-2 items-center">
          {" "}
          <h1 className="text-light-text text-[24px] font-bold">
            Вивантажити товари та/або змінити ціну <br /> додати опис до обраних
            товарів
          </h1>
          <Button onClick={() => {}} isActive={true} text="Вивантажити" />
        </div>
        <div className="flex gap-2 mt-3">
          <input
            value={s}
            onChange={(e) => setS(Number(e.target.value))}
            className="px-2 py-1 outline-0 border-1 rounded-[8px] shadow-sm"
            placeholder="Знижка у %"
            max={99}
            type="number"
          />
          <>
            {s != 0 && s != "" ? (
              <button onClick={() => setS("")}>
                <IconCancel />
              </button>
            ) : (
              ""
            )}
          </>
        </div>
        <div className="flex gap-2 mt-3">
          <textarea
            value={t}
            onChange={(e) => setT(e.target.value)}
            className="px-2 py-1 outline-0 border-1 rounded-[8px] shadow-sm w-[400px] min-h-[50px]"
            placeholder="Текст до опису"
          />
          <>
            {t.length ? (
              <button onClick={() => setT("")}>
                <IconCancel />
              </button>
            ) : (
              ""
            )}
          </>
        </div>
      </Wrapper>
    </>
  );
}
